### ISSUE TITLE
Not resigning

### ISSUE THREAD

**Issue by Clossius** [pdg137/random-move-bot#1]
After the change of forcing the bot to play longer, the bot does not resign. However, we do not want the bot to resign too early. 
https://online-go.com/game/69870452

**Comment by pdg137** [comment]
Thanks for the report. I guess we need to do something around here:

https://github.com/pdg137/random-move-bot/blob/master/random-move-bot.py#L12

Looks like returning [None, None] from the genmove function will cause it to pass.
